# RELEASE CONTROL

music_links: true
poster_embeds: true
paper_embeds: true
paper_videos: true

lbd_embeds: true

browse_paper_buttons: 0  # 0: none, 1: show

# Set to the current conference day

paper_day_release: 3
lbd_day_release: 0 # 0: none, 4: show

# CHANNEL METADATA

music_program_channel: '#music-program'
music_program_url: https://ismir2020.slack.com/archives/C01C4K3S0SU


name: ISMIR 2020
tagline: ISMIR 2020 <br> VIRTUAL <br> CONFERENCE
date: 11-16 October 2020
citation_date: 11-16 October 2020
proceedings_title: Proceedings of the First MiniCon Conference
analytics: UA-
logo:
  image: 'static/images/ISMIR-logo_Horizontal - Acronym only_RGB.jpg'
  width: 200px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: MiniConf
page_title:
  prefix: 'ISMIR 2020'
  separator: ': '
background_image: static/images/ISMIR_Homepage_HERO_IMAGE.png
organization: ISMIR Organization Committee

# Remove or change to your chat server.
chat_server: miniconf.sloppy.zone
default_presentation_id: 38922815
default_poster_pdf: /static/images/GLTR_poster.pdf


opening_ref_title_1: Opening Plenary A
opening_ref_title_2: Opening Plenary B (R)

# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    # qa: '#4FCAEB'
    # talk: '#ccc'
    # open: '#D9E6C0'
    # ind: '#F0EFEB'
    # key: '#B4CDED'
    tut: '#A79B8E'
    all: '#D50201'
    pos: '#F6BF25'
    meet: '#B39DDB'
    wimir: '#8F24AA'
    meet-spec: '#34B579'
    mus: '#3F51B5'
    master: '#BFCB33'
    sat: '#A79B8E'
  sunday_saturday: false  #  Include Sunday and Saturday
