name: Lint code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    # - name: Set up Python 3.7
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.7
    - name: Python attempt
      run: |
        cd scripts
        python3 test.py
    # - name: Use Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '12.x'
    # - name: Install NPM dependencies
    #   run: npm ci
    # - name: Format check
    #   run: make format-check
